/**
 * LLM API integration.
 *
 * The returned structure includes provider, model, text, and mock status so the
 * Sheet can preserve exactly what influenced the advisory evaluation.
 */

function callLlmWithRetry(prompt, config) {
  var lastError = null;

  for (var attempt = 1; attempt <= config.maxRetries; attempt++) {
    try {
      return callLlm_(prompt, config);
    } catch (error) {
      lastError = error;
      if (attempt < config.maxRetries) {
        Utilities.sleep(config.retryBaseMs * Math.pow(2, attempt - 1));
      }
    }
  }

  throw lastError;
}

function callLlm_(prompt, config) {
  if (config.llmProvider === 'anthropic') {
    if (!config.anthropicApiKey) {
      return buildMockLlmResponse_(config, 'Anthropic API key is not configured.');
    }
    return callAnthropic_(prompt, config);
  }

  if (!config.openAiApiKey) {
    return buildMockLlmResponse_(config, 'OpenAI API key is not configured.');
  }

  return callOpenAi_(prompt, config);
}

function callOpenAi_(prompt, config) {
  var payload = {
    model: config.openAiModel,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content: 'You produce vendor risk review JSON for human IT, Security, Legal, and Finance reviewers. Return JSON only.'
      },
      {
        role: 'user',
        content: prompt
      }
    ]
  };

  var response = UrlFetchApp.fetch('https://api.openai.com/v1/chat/completions', {
    method: 'post',
    muteHttpExceptions: true,
    contentType: 'application/json',
    headers: {
      Authorization: 'Bearer ' + config.openAiApiKey
    },
    payload: JSON.stringify(payload)
  });

  var statusCode = response.getResponseCode();
  var body = response.getContentText();

  if (statusCode < 200 || statusCode >= 300) {
    throw new Error('OpenAI API returned HTTP ' + statusCode + ': ' + body.substring(0, 500));
  }

  var parsed = JSON.parse(body);
  return {
    provider: 'openai',
    model: config.openAiModel,
    text: parsed.choices[0].message.content,
    rawApiResponse: body,
    mock: false
  };
}

function callAnthropic_(prompt, config) {
  var payload = {
    model: config.anthropicModel,
    max_tokens: 2000,
    system: 'You produce vendor risk review JSON for human IT, Security, Legal, and Finance reviewers. Return JSON only.',
    messages: [
      {
        role: 'user',
        content: prompt
      }
    ]
  };

  var response = UrlFetchApp.fetch('https://api.anthropic.com/v1/messages', {
    method: 'post',
    muteHttpExceptions: true,
    contentType: 'application/json',
    headers: {
      'x-api-key': config.anthropicApiKey,
      'anthropic-version': '2023-06-01'
    },
    payload: JSON.stringify(payload)
  });

  var statusCode = response.getResponseCode();
  var body = response.getContentText();

  if (statusCode < 200 || statusCode >= 300) {
    throw new Error('Anthropic API returned HTTP ' + statusCode + ': ' + body.substring(0, 500));
  }

  var parsed = JSON.parse(body);
  return {
    provider: 'anthropic',
    model: config.anthropicModel,
    text: parsed.content[0].text,
    rawApiResponse: body,
    mock: false
  };
}

function buildMockLlmResponse_(config, reason) {
  var response = {
    risk_rating: 'medium',
    recommendation: 'needs_manual_review',
    summary: 'MOCK LLM response used because the configured LLM API was unavailable. Human review is required before approval.',
    approval_gates: [
      {
        gate: 'manager',
        required: true,
        reason: 'Manager must confirm business need.'
      },
      {
        gate: 'business_owner',
        required: true,
        reason: 'A named owner must accept ongoing responsibility.'
      },
      {
        gate: 'it',
        required: true,
        reason: 'IT must review SSO, provisioning, deprovisioning, and supportability.'
      },
      {
        gate: 'security',
        required: true,
        reason: 'Security should review because the evaluation was not generated by a verified LLM response.'
      }
    ],
    key_risks: [
      {
        risk: 'Unverified automated evaluation',
        why_it_matters: 'SOC2 evidence should not rely on unavailable or mock model output.',
        severity: 'medium',
        mitigation: 'Complete manual vendor review and record notes in the evaluation Sheet.'
      }
    ],
    least_privilege_requirements: [
      'Use SSO if available.',
      'Assign only named admins.',
      'Require quarterly access review for non-SSO tools.'
    ],
    soc2_evidence_needed: [
      'Form response',
      'Manual security review notes',
      'Approval record',
      'Access owner'
    ],
    data_use_restrictions: [
      'Do not upload customer or production data until manual review is complete.'
    ],
    open_questions: [
      'Is SOC2 Type II available?',
      'Does the vendor support SSO and SCIM?',
      'Does the vendor use customer data for model training?'
    ],
    reviewer_notes: reason + ' This output is marked MOCK and must be treated as advisory only.'
  };

  return {
    provider: config.llmProvider,
    model: config.llmProvider === 'anthropic' ? config.anthropicModel : config.openAiModel,
    text: JSON.stringify(response),
    rawApiResponse: '',
    mock: true
  };
}
